# Generated by Django 4.2.13 on 2024-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_profile_picture_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/logo_technologies/'),
        ),
    ]
