# Generated by Django 4.2.13 on 2024-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
